In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('datasets/archive/movies_metadata.csv')

In [4]:
data.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
C = data['vote_average'].mean()

In [6]:
m = data['vote_count'].quantile(0.90)

160.0

In [7]:
q_movies = data.copy().loc[data['vote_count'] >= m]
q_movies.shape

(4555, 24)

In [8]:
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v*2) * C)

In [9]:
q_movies['score'] = q_movies.apply(weighted_rating, axis=1)

In [10]:
q_movies = q_movies.sort_values('score', ascending=False)
q_movies[['title', 'vote_count', 'vote_average', 'score']].head(50)

,title,vote_count,vote_average,score
314,The Shawshank Redemption,8358.0,8.5,8.393604
834,The Godfather,6024.0,8.5,8.353711
12481,The Dark Knight,12269.0,8.3,8.229549
2843,Fight Club,9678.0,8.3,8.211074
292,Pulp Fiction,8670.0,8.3,8.200970
522,Schindler's List,4436.0,8.3,8.110578
23673,Whiplash,4376.0,8.3,8.108097
351,Forrest Gump,8147.0,8.2,8.096693
5481,Spirited Away,3968.0,8.3,8.089326
2211,Life Is Beautiful,3643.0,8.3,8.071526
1154,The Empire Strikes Back,5998.0,8.2,8.060892
1178,The Godfather: Part II,3418.0,8.3,8.057333
18465,The Intouchables,5410.0,8.2,8.046321
15480,Inception,14075.0,8.1,8.040709
1152,One Flew Over the Cuckoo's Nest,3001.0,8.3,8.025760
22879,Interstellar,11187.0,8.1,8.025676
289,Leon: The Professional,4293.0,8.2,8.008147
3030,The Green Mile,4166.0,8.2,8.002572
7000,The Lord of the Rings: The Return of the King,8226.0,8.1,7.999569
256,Star Wars,6778.0,8.1,7.978740
1176,Psycho,2405.0,8.3,7.963129
46,Se7en,5915.0,8.1,7.961639
1170,GoodFellas,3211.0,8.2,7.947369
2216,American History X,3120.0,8.2,7.940455
10309,Dilwale Dulhania Le Jayenge,661.0,9.1,7.933107
586,The Silence of the Lambs,4549.0,8.1,7.921878
4863,The Lord of the Rings: The Fellowship of the Ring,8892.0,8.0,7.908690
4099,Memento,4168.0,8.1,7.906359
5814,The Lord of the Rings: The Two Towers,7641.0,8.0,7.894131
1213,The Shining,3890.0,8.1,7.893213
1057,Reservoir Dogs,3821.0,8.1,7.889669
1225,Back to the Future,6239.0,8.0,7.871097
24860,The Imitation Game,5895.0,8.0,7.863827
49,The Usual Suspects,3334.0,8.1,7.860729
359,The Lion King,5520.0,8.0,7.854908
1161,12 Angry Men,2130.0,8.2,7.830448
22841,The Grand Budapest Hotel,4644.0,8.0,7.828699
11354,The Prestige,4510.0,8.0,7.823831
32144,Room,2838.0,8.1,7.821741
23753,Guardians of the Galaxy,10014.0,7.9,7.820289
9698,Howl's Moving Castle,2049.0,8.2,7.817178
1201,Dead Poets Society,2786.0,8.1,7.816905
2884,Princess Mononoke,2041.0,8.2,7.815815
2458,The Matrix,9079.0,7.9,7.812261
109,Taxi Driver,2632.0,8.1,7.801545
22131,The Wolf of Wall Street,6768.0,7.9,7.783185
30315,Inside Out,6737.0,7.9,7.782664
5878,City of God,1852.0,8.2,7.780551
13605,Inglourious Basterds,6598.0,7.9,7.780266
17437,Harry Potter and the Deathly Hallows: Part 2,6141.0,7.9,7.771645

In [11]:
data['overview'].head()

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

data['overview'] = data['overview'].fillna('')

tfidf_matrix = tfidf.fit_transform(data['overview'])

tfidf_matrix.shape

(45466, 75827)

In [13]:
tfidf.get_feature_names()[5000:5010]

c:\users\rhars\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['avails',
 'avaks',
 'avalanche',
 'avalanches',
 'avallone',
 'avalon',
 'avant',
 'avanthika',
 'avanti',
 'avaracious']

In [14]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [15]:
indices = pd.Series(data.index, index=data['title']).drop_duplicates()

In [16]:
def get_recommendations(title, cosine_sim=cosine_sim):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return data['title'].iloc[movie_indices]

In [79]:
get_recommendations('The Imitation Game')

25077                       Codebreaker
36522                    Nightmare Code
5286                        Windtalkers
30600                     Lick the Star
32012                       Dog Eat Dog
24171                     Brother's War
16617               The Code Conspiracy
36210                         The Thorn
1726                     Mercury Rising
17443    Snow Flower and the Secret Fan
Name: title, dtype: object